use_frameworks!

target 'SDViewHelper_Example' do
  pod 'SDViewHelper', :path => '../'

#  target 'SDViewHelper_Tests' do
#    inherit! :search_paths

#    pod 'Specta'
#  pod 'Expecta'
#  pod 'FBSnapshotTestCase'
#  pod 'Expecta+Snapshots'
#  end
end
